export const INFLUENCER_DATA = [
  // Instagram - Micro/Macro
  {
    name: "Sakshi Sindwani",
    handle: "stylemeupwithsakshi",
    city: "New Delhi",
    state: "DL",
    gender: "Female",
    bio: "Body Positivity & Fashion",
    niches: ["Fashion", "Lifestyle"],
    platforms: ["Instagram", "YouTube"],
    primaryPlatform: "Instagram",
    followers: 650000,
    posts: 1200,
    likes: 15000,
    engagement: 4.5,
    startingPrice: 150000,
    isVerified: true,
    socialLinks: { instagram: "https://instagram.com/stylemeupwithsakshi" },
  },
  {
    name: "Vishnu Kaushal",
    handle: "thevishnukaushal",
    city: "Chandigarh",
    state: "CH",
    gender: "Male",
    bio: "Comedy & Relatable Content",
    niches: ["Comedy", "Lifestyle"],
    platforms: ["Instagram", "YouTube"],
    primaryPlatform: "Instagram",
    followers: 2400000,
    posts: 400,
    likes: 250000,
    engagement: 11.2,
    startingPrice: 350000,
    isVerified: true,
    socialLinks: { instagram: "https://instagram.com/thevishnukaushal" },
  },
  {
    name: "Kritika Khurana",
    handle: "thatbohogirl",
    city: "New Delhi",
    state: "DL",
    gender: "Female",
    bio: "Fashion & Travel",
    niches: ["Fashion", "Travel"],
    platforms: ["Instagram", "YouTube"],
    primaryPlatform: "Instagram",
    followers: 1700000,
    posts: 2800,
    likes: 50000,
    engagement: 3.8,
    startingPrice: 200000,
    isVerified: true,
    socialLinks: { instagram: "https://instagram.com/thatbohogirl" },
  },
  {
    name: "Anunay Sood",
    handle: "anunaysood",
    city: "New Delhi",
    state: "DL",
    gender: "Male",
    bio: "Travel Filmmaker",
    niches: ["Travel", "Lifestyle"],
    platforms: ["Instagram", "YouTube"],
    primaryPlatform: "Instagram",
    followers: 1100000,
    posts: 950,
    likes: 120000,
    engagement: 8.5,
    startingPrice: 250000,
    isVerified: true,
    socialLinks: { instagram: "https://instagram.com/anunaysood" },
  },
  {
    name: "Shivesh Bhatia",
    handle: "shivesh17",
    city: "New Delhi",
    state: "DL",
    gender: "Male",
    bio: "Food Blogger & Baker",
    niches: ["Food", "Lifestyle"],
    platforms: ["Instagram", "YouTube"],
    primaryPlatform: "Instagram",
    followers: 1300000,
    posts: 3500,
    likes: 45000,
    engagement: 5.2,
    startingPrice: 180000,
    isVerified: true,
    socialLinks: { instagram: "https://instagram.com/shivesh17" },
  },
  {
    name: "Saloni Gaur",
    handle: "salonayyy",
    city: "New Delhi",
    state: "DL",
    gender: "Female",
    bio: "Comedy & Satire",
    niches: ["Comedy", "Entertainment"],
    platforms: ["Instagram", "YouTube"],
    primaryPlatform: "Instagram",
    followers: 1200000,
    posts: 500,
    likes: 80000,
    engagement: 7.1,
    startingPrice: 150000,
    isVerified: true,
    socialLinks: { instagram: "https://instagram.com/salonayyy" },
  },
  {
    name: "Ruhee Dosani",
    handle: "ruheedosani",
    city: "Mumbai",
    state: "MH",
    gender: "Female",
    bio: "We desis everywhere",
    niches: ["Comedy", "Entertainment"],
    platforms: ["Instagram", "YouTube"],
    primaryPlatform: "Instagram",
    followers: 2800000,
    posts: 320,
    likes: 400000,
    engagement: 14.5,
    startingPrice: 400000,
    isVerified: true,
    socialLinks: { instagram: "https://instagram.com/ruheedosani" },
  },

  // YouTube - Micro/Macro
  {
    name: "Slayy Point",
    handle: "SlayyPoint",
    city: "Mumbai",
    state: "MH",
    gender: "Other",
    bio: "Gauti and Abhi",
    niches: ["Comedy", "Entertainment"],
    platforms: ["YouTube", "Instagram"],
    primaryPlatform: "YouTube",
    followers: 8200000, 
    posts: 250,
    likes: 500000,
    engagement: 12.0,
    startingPrice: 800000,
    isVerified: true,
    socialLinks: { youtube: "https://youtube.com/@SlayyPoint" },
  },
  {
    name: "Sanjhalika Shokeen",
    handle: "SanjhalikaVlogs",
    city: "New Delhi",
    state: "DL",
    gender: "Female",
    bio: "Daily Vlogs",
    niches: ["Lifestyle", "Comedy"],
    platforms: ["YouTube", "Instagram"],
    primaryPlatform: "YouTube",
    followers: 2500000,
    posts: 400,
    likes: 120000,
    engagement: 8.5,
    startingPrice: 300000,
    isVerified: true,
    socialLinks: { youtube: "https://youtube.com/@SanjhalikaVlogs" },
  },
  {
    name: "Beebom",
    handle: "Beebomco",
    city: "New Delhi",
    state: "DL",
    gender: "Male",
    bio: "Tech that matters",
    niches: ["Tech"],
    platforms: ["YouTube", "Instagram", "X (Twitter)"],
    primaryPlatform: "YouTube",
    followers: 3500000,
    posts: 1200,
    likes: 80000,
    engagement: 6.5,
    startingPrice: 450000,
    isVerified: true,
    socialLinks: { youtube: "https://youtube.com/@Beebomco" },
  },
  {
    name: "Your Food Lab",
    handle: "YourFoodLab",
    city: "Mumbai",
    state: "MH",
    gender: "Male",
    bio: "Chef Sanjyot Keer",
    niches: ["Food", "Lifestyle"],
    platforms: ["YouTube", "Instagram"],
    primaryPlatform: "YouTube",
    followers: 4800000,
    posts: 800,
    likes: 150000,
    engagement: 7.2,
    startingPrice: 500000,
    isVerified: true,
    socialLinks: { youtube: "https://youtube.com/@YourFoodLab" },
  },
  {
    name: "Sharan Hegde",
    handle: "financewithsharan",
    city: "Bangalore",
    state: "KA",
    gender: "Male",
    bio: "Finance made fun",
    niches: ["Education", "Business"],
    platforms: ["YouTube", "Instagram", "LinkedIn"],
    primaryPlatform: "Instagram",
    followers: 2200000,
    posts: 450,
    likes: 150000,
    engagement: 9.8,
    startingPrice: 350000,
    isVerified: true,
    socialLinks: { youtube: "https://youtube.com/@financewithsharan" },
  },

  // LinkedIn
  {
    name: "Akshat Shrivastava",
    handle: "akshatshrivastava",
    city: "New Delhi",
    state: "DL",
    gender: "Male",
    bio: "Finance and Business",
    niches: ["Education", "Business"],
    platforms: ["LinkedIn", "YouTube"],
    primaryPlatform: "LinkedIn",
    followers: 850000,
    posts: 350,
    likes: 12000,
    engagement: 4.5,
    startingPrice: 200000,
    isVerified: true,
    socialLinks: { linkedin: "https://linkedin.com/in/akshatshrivastava" },
  },
  {
    name: "Vaibhav Sisinty",
    handle: "vaibhavsisinty",
    city: "Bangalore",
    state: "KA",
    gender: "Male",
    bio: "Growth Hacker",
    niches: ["Education", "Business"],
    platforms: ["LinkedIn", "X (Twitter)"],
    primaryPlatform: "LinkedIn",
    followers: 450000,
    posts: 600,
    likes: 5000,
    engagement: 3.2,
    startingPrice: 100000,
    isVerified: true,
    socialLinks: { linkedin: "https://linkedin.com/in/vaibhavsisinty" },
  },
  {
    name: "Aman Dhattarwal",
    handle: "amandhattarwal",
    city: "New Delhi",
    state: "DL",
    gender: "Male",
    bio: "Educator & Entrepreneur",
    niches: ["Education", "Tech"],
    platforms: ["LinkedIn", "YouTube"],
    primaryPlatform: "YouTube",
    followers: 650000,
    posts: 200,
    likes: 8000,
    engagement: 5.5,
    startingPrice: 250000,
    isVerified: true,
    socialLinks: { linkedin: "https://linkedin.com/in/amandhattarwal" },
  },
  
  // X (Twitter)
  {
    name: "Abhishek Asthana",
    handle: "GabbbarSingh",
    city: "New Delhi",
    state: "DL",
    gender: "Male",
    bio: "Marketer & Satirist",
    niches: ["Comedy", "Business"],
    platforms: ["X (Twitter)", "LinkedIn"],
    primaryPlatform: "X (Twitter)",
    followers: 1400000,
    posts: 25000,
    likes: 8000,
    engagement: 2.5,
    startingPrice: 120000,
    isVerified: true,
    socialLinks: { twitter: "https://x.com/GabbbarSingh" },
  },
  {
    name: "Ritu Rathod",
    handle: "RituRathod",
    city: "Mumbai",
    state: "MH",
    gender: "Female",
    bio: "Finance & Investing",
    niches: ["Education", "Business"],
    platforms: ["X (Twitter)"],
    primaryPlatform: "X (Twitter)",
    followers: 350000,
    posts: 5000,
    likes: 2000,
    engagement: 1.8,
    startingPrice: 50000,
    isVerified: false,
    socialLinks: { twitter: "https://x.com/RituRathod" },
  },

  // Facebook (Pages/Creators)
  {
    name: "The Indian Idiot",
    handle: "theindianidiot",
    city: "Mumbai",
    state: "MH",
    gender: "Other",
    bio: "Memes & Pop Culture",
    niches: ["Comedy", "Entertainment"],
    platforms: ["Facebook", "Instagram"],
    primaryPlatform: "Instagram", 
    followers: 2500000,
    posts: 4500,
    likes: 20000,
    engagement: 4.2,
    startingPrice: 80000,
    isVerified: true,
    socialLinks: { facebook: "https://facebook.com/theindianidiot" },
  }
].map(inf => {
  // Generate hashtags
  const MOCK_HASHTAGS = ["#fashion", "#style", "#ootd", "#travel", "#lifestyle", "#beauty", "#makeup", "#food", "#fitness", "#gym", "#workout", "#motivation", "#inspiration", "#photography", "#art", "#design", "#home", "#decor", "#interiors", "#love", "#happy", "#cute", "#beautiful", "#nature"];
  const hashtags = [...MOCK_HASHTAGS].sort(() => 0.5 - Math.random()).slice(0, 15 + Math.floor(Math.random() * 5));
  
  const MOCK_MENTIONS = ["@zara", "@hm", "@nike", "@adidas", "@puma", "@mac", "@sephora", "@nyx", "@fenty", "@glossier", "@airbnb", "@bookingcom", "@expedia", "@tripadvisor", "@uber", "@lyft", "@doordash", "@ubereats", "@postmates", "@grubhub"];
  const mentions = [...MOCK_MENTIONS].sort(() => 0.5 - Math.random()).slice(0, 15 + Math.floor(Math.random() * 5));

  // Generate growth history (12 months)
  const growthHistory = [];
  let currentFollowers = Math.floor(inf.followers * 0.5);
  for (let i = 11; i >= 0; i--) {
    const d = new Date();
    d.setMonth(d.getMonth() - i);
    growthHistory.push({
      date: d.toISOString().split('T')[0],
      followers: currentFollowers,
      posts: Math.floor(inf.posts * (1 - (i/12))),
    });
    currentFollowers += Math.floor((inf.followers - currentFollowers) / (i + 1));
  }

  // Generate daily stats (last 7 days)
  const dailyStats = [];
  for (let i = 6; i >= 0; i--) {
    const d = new Date();
    d.setDate(d.getDate() - i);
    dailyStats.push({
      date: d.toISOString().split('T')[0],
      likes: Math.floor(inf.likes * (Math.random() * 0.5 + 0.5)),
      comments: Math.floor(inf.likes * 0.1 * (Math.random() * 0.5 + 0.5)),
      posts: Math.random() > 0.5 ? 1 : 0,
      videos: Math.random() > 0.8 ? 1 : 0,
    });
  }

  // Generate recent posts (12 items)
  const recentPosts = [];
  for (let i = 0; i < 12; i++) {
    const d = new Date();
    d.setDate(d.getDate() - i * 2);
    recentPosts.push({
      imageUrl: `https://api.dicebear.com/7.x/shapes/svg?seed=${inf.name.replace(/\s/g, '')}${i}&backgroundColor=e2e8f0`,
      likes: Math.floor(inf.likes * (Math.random() * 0.5 + 0.5)),
      comments: Math.floor(inf.likes * 0.1 * (Math.random() * 0.5 + 0.5)),
      date: d.toISOString().split('T')[0]
    });
  }

  return {
    ...inf,
    hashtags,
    mentions,
    growthHistory,
    dailyStats,
    recentPosts
  };
});
